name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: code
        run: |
          git clone -b dev https://github.com/SagerNet/sing sing
          git clone -b building https://github.com/White12352/pasi t
          rm -f sing/protocol/http/client.go
          cp -f t/protocol/http/client.go sing/protocol/http
          rm -rf t
          cd sing
          #git config user.email "github-actions@github.com"
          #git config user.name "GitHub Actions"
          #git revert a23e4e5
          rm -f common/bufio/addr_conn.go  
          cd ..
      
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b dev
          rm -rf .github
          cp -r sing/* .
          cp -r sing/.github .
          rm -rf sing
          git add .
          git commit -m "commit"
          git push --force origin dev
